---
title: Natual Awesome
email: your-email@domain.com
url: https://example.github.io
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
skills: 내추럴 어썸 - 친환경 제품 모아보기
meta_author: LastName FirstName
google_verify: 
bing_verify: 
contact: disqus
disqus_shortname: natural-list
color:
  primary: 18bc9c
  primary-rgb: '24,288,156'
  secondary: 2c3e50
  secondary-dark: 233140
footer:
  copyright: 큐레이터스
  location: Location
  social: Around the Web
  credits: Credits
social:
- title: twitter
  url: 
- title: facebook
  url: 
- title: github
  url: 
address:
- line: 큐레이터스 프로젝트
credits: Hosted by GitHub
markdown: kramdown
permalink: pretty
